### ISSUE TITLE
Downloading UI5 applications from NW ABAP

### ISSUE THREAD

**Issue by professionally** [pfefferf/grunt-nwabap-ui5uploader#42]
Actually it's not an issue, I just want to talk about a new feature.

The upload is working like a charm but what I'm missing is to retrieve BSP applications from the Netweaver ABAP System.

At the moment I work with Eclipse because you can retrieve existing BSP applications from an ABAP system.
The same feature would be awesome. 
So build up a connection and retrieve the in gruntfile-options given BSP name.

Would be nice

**Comment by pfefferf** [comment]
Personally I do not see really a relevance for that feature in a modern development environment, because the source is managed via a Git Repo and not via a BSP application.  Additionally in case when only builded sources are deployed to the BSP application (which should be the default case), you will not get the sources you poentially wanna modify.
